// Code generated by MockGen. DO NOT EDIT.
// Source: service/equipments_service/equipments_repo.go

// Package mock_equipments_service is a generated GoMock package.
package mock_equipments_service

import (
	equipments_service "Manufacturing-Supplier-Portal/service/equipments_service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEquipmentsRepo is a mock of EquipmentsRepo interface.
type MockEquipmentsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEquipmentsRepoMockRecorder
}

// MockEquipmentsRepoMockRecorder is the mock recorder for MockEquipmentsRepo.
type MockEquipmentsRepoMockRecorder struct {
	mock *MockEquipmentsRepo
}

// NewMockEquipmentsRepo creates a new mock instance.
func NewMockEquipmentsRepo(ctrl *gomock.Controller) *MockEquipmentsRepo {
	mock := &MockEquipmentsRepo{ctrl: ctrl}
	mock.recorder = &MockEquipmentsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEquipmentsRepo) EXPECT() *MockEquipmentsRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEquipmentsRepo) Create(data equipments_service.Equipments) (equipments_service.Equipments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(equipments_service.Equipments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEquipmentsRepoMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEquipmentsRepo)(nil).Create), data)
}

// Delete mocks base method.
func (m *MockEquipmentsRepo) Delete(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEquipmentsRepoMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEquipmentsRepo)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockEquipmentsRepo) GetAll() ([]equipments_service.Equipments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]equipments_service.Equipments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockEquipmentsRepoMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockEquipmentsRepo)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockEquipmentsRepo) GetById(id int) (equipments_service.Equipments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(equipments_service.Equipments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockEquipmentsRepoMockRecorder) GetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockEquipmentsRepo)(nil).GetById), id)
}

// Update mocks base method.
func (m *MockEquipmentsRepo) Update(id int, data equipments_service.Equipments) (equipments_service.Equipments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, data)
	ret0, _ := ret[0].(equipments_service.Equipments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEquipmentsRepoMockRecorder) Update(id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEquipmentsRepo)(nil).Update), id, data)
}

// UpdateStatus mocks base method.
func (m *MockEquipmentsRepo) UpdateStatus(id int, status bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockEquipmentsRepoMockRecorder) UpdateStatus(id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockEquipmentsRepo)(nil).UpdateStatus), id, status)
}
