// Code generated by MockGen. DO NOT EDIT.
// Source: service/rentals_service/rentals_repo.go

// Package mock_rentals_service is a generated GoMock package.
package mock_rentals_service

import (
	model "Manufacturing-Supplier-Portal/model"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRentalsRepo is a mock of RentalsRepo interface.
type MockRentalsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRentalsRepoMockRecorder
}

// MockRentalsRepoMockRecorder is the mock recorder for MockRentalsRepo.
type MockRentalsRepoMockRecorder struct {
	mock *MockRentalsRepo
}

// NewMockRentalsRepo creates a new mock instance.
func NewMockRentalsRepo(ctrl *gomock.Controller) *MockRentalsRepo {
	mock := &MockRentalsRepo{ctrl: ctrl}
	mock.recorder = &MockRentalsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRentalsRepo) EXPECT() *MockRentalsRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRentalsRepo) Create(data model.Rentals) (model.Rentals, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.Rentals)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRentalsRepoMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRentalsRepo)(nil).Create), data)
}

// GetRentalById mocks base method.
func (m *MockRentalsRepo) GetRentalById(id int) (model.RentalEquipmentUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRentalById", id)
	ret0, _ := ret[0].(model.RentalEquipmentUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRentalById indicates an expected call of GetRentalById.
func (mr *MockRentalsRepoMockRecorder) GetRentalById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRentalById", reflect.TypeOf((*MockRentalsRepo)(nil).GetRentalById), id)
}

// SimulateAutomaticUpdateRentalStatus mocks base method.
func (m *MockRentalsRepo) SimulateAutomaticUpdateRentalStatus() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SimulateAutomaticUpdateRentalStatus")
	ret0, _ := ret[0].(error)
	return ret0
}

// SimulateAutomaticUpdateRentalStatus indicates an expected call of SimulateAutomaticUpdateRentalStatus.
func (mr *MockRentalsRepoMockRecorder) SimulateAutomaticUpdateRentalStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimulateAutomaticUpdateRentalStatus", reflect.TypeOf((*MockRentalsRepo)(nil).SimulateAutomaticUpdateRentalStatus))
}

// UpdateStatusAndDateRepo mocks base method.
func (m *MockRentalsRepo) UpdateStatusAndDateRepo(id int, status string, startDate, endDate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusAndDateRepo", id, status, startDate, endDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusAndDateRepo indicates an expected call of UpdateStatusAndDateRepo.
func (mr *MockRentalsRepoMockRecorder) UpdateStatusAndDateRepo(id, status, startDate, endDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusAndDateRepo", reflect.TypeOf((*MockRentalsRepo)(nil).UpdateStatusAndDateRepo), id, status, startDate, endDate)
}
