// Code generated by MockGen. DO NOT EDIT.
// Source: service/xendit_service/xendit_repo.go

// Package mock_xendit_service is a generated GoMock package.
package mock_xendit_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockXenditRepo is a mock of XenditRepo interface.
type MockXenditRepo struct {
	ctrl     *gomock.Controller
	recorder *MockXenditRepoMockRecorder
}

// MockXenditRepoMockRecorder is the mock recorder for MockXenditRepo.
type MockXenditRepoMockRecorder struct {
	mock *MockXenditRepo
}

// NewMockXenditRepo creates a new mock instance.
func NewMockXenditRepo(ctrl *gomock.Controller) *MockXenditRepo {
	mock := &MockXenditRepo{ctrl: ctrl}
	mock.recorder = &MockXenditRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXenditRepo) EXPECT() *MockXenditRepoMockRecorder {
	return m.recorder
}

// XenditInvoiceUrl mocks base method.
func (m *MockXenditRepo) XenditInvoiceUrl(userId, description, username, email, name, category string, paymentId int, amount float64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XenditInvoiceUrl", userId, description, username, email, name, category, paymentId, amount)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// XenditInvoiceUrl indicates an expected call of XenditInvoiceUrl.
func (mr *MockXenditRepoMockRecorder) XenditInvoiceUrl(userId, description, username, email, name, category, paymentId, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XenditInvoiceUrl", reflect.TypeOf((*MockXenditRepo)(nil).XenditInvoiceUrl), userId, description, username, email, name, category, paymentId, amount)
}
