// Code generated by MockGen. DO NOT EDIT.
// Source: service/payments_service/payments_repo.go

// Package mock_payments_service is a generated GoMock package.
package mock_payments_service

import (
	model "Manufacturing-Supplier-Portal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPaymentsRepo is a mock of PaymentsRepo interface.
type MockPaymentsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentsRepoMockRecorder
}

// MockPaymentsRepoMockRecorder is the mock recorder for MockPaymentsRepo.
type MockPaymentsRepoMockRecorder struct {
	mock *MockPaymentsRepo
}

// NewMockPaymentsRepo creates a new mock instance.
func NewMockPaymentsRepo(ctrl *gomock.Controller) *MockPaymentsRepo {
	mock := &MockPaymentsRepo{ctrl: ctrl}
	mock.recorder = &MockPaymentsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentsRepo) EXPECT() *MockPaymentsRepoMockRecorder {
	return m.recorder
}

// BookingReport mocks base method.
func (m *MockPaymentsRepo) BookingReport() ([]model.BookingsReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookingReport")
	ret0, _ := ret[0].([]model.BookingsReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BookingReport indicates an expected call of BookingReport.
func (mr *MockPaymentsRepoMockRecorder) BookingReport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookingReport", reflect.TypeOf((*MockPaymentsRepo)(nil).BookingReport))
}

// Create mocks base method.
func (m *MockPaymentsRepo) Create(data model.Payments) (model.Payments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", data)
	ret0, _ := ret[0].(model.Payments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPaymentsRepoMockRecorder) Create(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPaymentsRepo)(nil).Create), data)
}

// GetAll mocks base method.
func (m *MockPaymentsRepo) GetAll(userId string) ([]model.Payments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", userId)
	ret0, _ := ret[0].([]model.Payments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPaymentsRepoMockRecorder) GetAll(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPaymentsRepo)(nil).GetAll), userId)
}

// GetById mocks base method.
func (m *MockPaymentsRepo) GetById(id int, userId string) (model.Payments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id, userId)
	ret0, _ := ret[0].(model.Payments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockPaymentsRepoMockRecorder) GetById(id, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockPaymentsRepo)(nil).GetById), id, userId)
}

// UpdateStatusAndMethod mocks base method.
func (m *MockPaymentsRepo) UpdateStatusAndMethod(id int, status, method string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusAndMethod", id, status, method)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusAndMethod indicates an expected call of UpdateStatusAndMethod.
func (mr *MockPaymentsRepoMockRecorder) UpdateStatusAndMethod(id, status, method interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusAndMethod", reflect.TypeOf((*MockPaymentsRepo)(nil).UpdateStatusAndMethod), id, status, method)
}
