// Code generated by MockGen. DO NOT EDIT.
// Source: service/rental_histories_service/rental_histories_repo.go

// Package mock_rental_histories_service is a generated GoMock package.
package mock_rental_histories_service

import (
	rental_histories_service "Manufacturing-Supplier-Portal/service/rental_histories_service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRentalHistoriesRepo is a mock of RentalHistoriesRepo interface.
type MockRentalHistoriesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRentalHistoriesRepoMockRecorder
}

// MockRentalHistoriesRepoMockRecorder is the mock recorder for MockRentalHistoriesRepo.
type MockRentalHistoriesRepoMockRecorder struct {
	mock *MockRentalHistoriesRepo
}

// NewMockRentalHistoriesRepo creates a new mock instance.
func NewMockRentalHistoriesRepo(ctrl *gomock.Controller) *MockRentalHistoriesRepo {
	mock := &MockRentalHistoriesRepo{ctrl: ctrl}
	mock.recorder = &MockRentalHistoriesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRentalHistoriesRepo) EXPECT() *MockRentalHistoriesRepoMockRecorder {
	return m.recorder
}

// CreateRentalHistory mocks base method.
func (m *MockRentalHistoriesRepo) CreateRentalHistory(data rental_histories_service.RentalHistories) (rental_histories_service.RentalHistories, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRentalHistory", data)
	ret0, _ := ret[0].(rental_histories_service.RentalHistories)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRentalHistory indicates an expected call of CreateRentalHistory.
func (mr *MockRentalHistoriesRepoMockRecorder) CreateRentalHistory(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRentalHistory", reflect.TypeOf((*MockRentalHistoriesRepo)(nil).CreateRentalHistory), data)
}

// GetAll mocks base method.
func (m *MockRentalHistoriesRepo) GetAll(userId string) ([]rental_histories_service.RentalHistories, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", userId)
	ret0, _ := ret[0].([]rental_histories_service.RentalHistories)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRentalHistoriesRepoMockRecorder) GetAll(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRentalHistoriesRepo)(nil).GetAll), userId)
}
